<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Post;

class PostSeeder extends Seeder
{
    public function run()
    {
        $articles = $this->getArticles();
        $baseDate = now()->subDays(count($articles));

        foreach ($articles as $i => $a) {
            Post::create([
                'title'      => $a[0],
                'des'        => $a[1],
                'content'    => $a[2],
                'created_at' => $baseDate->copy()->addDays($i)->addHours(rand(7,20))->addMinutes(rand(0,59)),
                'updated_at' => $baseDate->copy()->addDays($i)->addHours(rand(7,20))->addMinutes(rand(0,59)),
            ]);
        }
    }

    private function getArticles(): array
    {
        return [
            $this->a('Giá vàng hôm nay: Tăng mạnh vượt mốc 5.100 USD/ounce','Giá vàng thế giới tiếp tục leo thang trong bối cảnh lo ngại lạm phát và bất ổn địa chính trị.','<h2>Giá vàng tăng mạnh</h2><p>Giá vàng thế giới hôm nay đã vượt mốc 5.100 USD/ounce, đánh dấu mức cao kỷ lục mới trong lịch sử. Nguyên nhân chính đến từ lo ngại lạm phát tại Mỹ và châu Âu, cùng với sự bất ổn địa chính trị toàn cầu.</p><h3>Nguyên nhân tăng giá</h3><p>Các chuyên gia phân tích chỉ ra rằng dòng tiền đang đổ mạnh vào vàng như một kênh trú ẩn an toàn. Ngân hàng trung ương nhiều nước tiếp tục mua vàng dự trữ, đặc biệt là Trung Quốc và Ấn Độ.</p><h3>Dự báo</h3><p>ANZ dự báo vàng có thể đạt 5.800 USD/ounce trong quý 2, trong khi Goldman Sachs thận trọng hơn với mức 5.500 USD.</p>'),
            $this->a('Bạc tăng giá kỷ lục: Cơ hội đầu tư không nên bỏ lỡ','Giá bạc đạt mức cao nhất trong 10 năm, thu hút sự quan tâm của nhà đầu tư.','<h2>Bạc lập đỉnh mới</h2><p>Giá bạc thế giới vừa chạm mốc 38 USD/ounce, mức cao nhất kể từ năm 2016. Đây là tín hiệu tích cực cho những nhà đầu tư đã kiên nhẫn nắm giữ kim loại quý này.</p><h3>Tại sao bạc tăng?</h3><p>Nhu cầu bạc trong công nghiệp, đặc biệt là sản xuất pin năng lượng mặt trời và xe điện, đang tăng mạnh. Cùng với vai trò trú ẩn an toàn, bạc đang hưởng lợi kép.</p><p>Tỷ lệ vàng/bạc hiện ở mức 134:1, cho thấy bạc vẫn còn rẻ so với vàng và có tiềm năng tăng trưởng lớn.</p>'),
            $this->a('Phân tích kỹ thuật: Vàng điều chỉnh ngắn hạn trước báo cáo CPI','Vàng giảm nhẹ trước khi Mỹ công bố chỉ số giá tiêu dùng, nhà đầu tư thận trọng.','<h2>Vàng điều chỉnh trước CPI</h2><p>Giá vàng giảm khoảng 1,2% trong phiên giao dịch châu Á khi nhà đầu tư chốt lời trước báo cáo CPI quan trọng của Mỹ. Đây là đợt điều chỉnh kỹ thuật bình thường sau chuỗi tăng giá kéo dài.</p><h3>Các mức hỗ trợ quan trọng</h3><p>Theo phân tích kỹ thuật, vàng có hỗ trợ mạnh tại 4.950 USD/ounce. Nếu mất mốc này, giá có thể test lại vùng 4.800 USD. Ngược lại, vượt 5.150 USD sẽ mở đường lên 5.300 USD.</p>'),
            $this->a('Ngân hàng trung ương Trung Quốc tiếp tục mua vàng tháng thứ 18','PBOC mua thêm 12 tấn vàng trong tháng 2, nâng tổng dự trữ lên mức kỷ lục.','<h2>Trung Quốc tăng dự trữ vàng</h2><p>Ngân hàng Nhân dân Trung Quốc (PBOC) đã mua thêm 12 tấn vàng trong tháng 2/2026, đánh dấu tháng mua ròng thứ 18 liên tiếp. Tổng dự trữ vàng của Trung Quốc hiện đạt hơn 2.500 tấn.</p><h3>Xu hướng toàn cầu</h3><p>Không chỉ Trung Quốc, các ngân hàng trung ương trên toàn thế giới đã mua hơn 1.000 tấn vàng trong năm 2025, con số cao kỷ lục. Điều này phản ánh xu hướng đa dạng hóa dự trữ ngoại hối và giảm phụ thuộc vào đồng USD.</p>'),
            $this->a('So sánh đầu tư vàng và bạc: Đâu là lựa chọn tốt hơn năm 2026?','Phân tích chi tiết ưu nhược điểm khi đầu tư vàng vs bạc trong bối cảnh thị trường hiện tại.','<h2>Vàng hay bạc?</h2><p>Câu hỏi đầu tư vàng hay bạc luôn là chủ đề nóng. Mỗi kim loại quý đều có những ưu điểm riêng, và lựa chọn phụ thuộc vào mục tiêu đầu tư của bạn.</p><h3>Vàng — Ổn định và an toàn</h3><p>Vàng là tài sản trú ẩn truyền thống, biến động ít hơn bạc. Phù hợp cho nhà đầu tư thận trọng, muốn bảo toàn vốn dài hạn.</p><h3>Bạc — Tiềm năng tăng trưởng cao</h3><p>Bạc có biên độ dao động lớn hơn, mang lại cơ hội lợi nhuận cao hơn (và rủi ro cao hơn). Nhu cầu công nghiệp tăng mạnh là động lực chính.</p><h3>Lời khuyên</h3><p>Danh mục đầu tư lý tưởng nên kết hợp cả hai, với tỷ lệ 70% vàng và 30% bạc.</p>'),
            $this->a('Giá vàng trong nước: SJC vượt 90 triệu đồng/lượng','Giá vàng miếng SJC tiếp tục tăng mạnh, khoảng cách với giá thế giới ngày càng lớn.','<h2>Vàng SJC lập kỷ lục mới</h2><p>Giá vàng miếng SJC hôm nay được các doanh nghiệp niêm yết ở mức 89,5 - 91,2 triệu đồng/lượng (mua - bán), tăng 800.000 đồng so với hôm qua.</p><h3>Chênh lệch với thế giới</h3><p>Hiện chênh lệch giữa giá vàng SJC và giá thế giới quy đổi lên tới 15-18 triệu đồng/lượng. Đây là mức chênh lệch rất lớn, phản ánh nguồn cung vàng miếng trong nước hạn chế.</p>'),
            $this->a('5 sai lầm phổ biến khi đầu tư vàng mà người mới hay mắc phải','Tránh những sai lầm này để bảo vệ tiền của bạn khi bắt đầu đầu tư vàng.','<h2>Sai lầm khi đầu tư vàng</h2><p>Đầu tư vàng tưởng đơn giản nhưng nhiều người mới vẫn mắc phải những sai lầm cơ bản, dẫn đến thua lỗ không đáng có.</p><h3>1. Mua khi giá đang tăng nóng</h3><p>Tâm lý FOMO khiến nhiều người mua vàng khi giá đang ở đỉnh. Hãy kiên nhẫn chờ đợi đợt điều chỉnh.</p><h3>2. Không phân bổ danh mục</h3><p>Bỏ hết trứng vào một giỏ là sai lầm lớn. Vàng chỉ nên chiếm 10-20% danh mục đầu tư.</p><h3>3. Mua vàng trang sức để đầu tư</h3><p>Vàng trang sức có phí gia công cao, khi bán lại sẽ mất giá đáng kể. Nên mua vàng miếng hoặc nhẫn trơn.</p><h3>4. Không kiểm tra nguồn gốc</h3><p>Luôn mua vàng tại các thương hiệu uy tín có hóa đơn và giấy chứng nhận.</p><h3>5. Giao dịch quá thường xuyên</h3><p>Mua bán liên tục sẽ mất phí chênh lệch giá mua-bán. Vàng phù hợp cho đầu tư dài hạn.</p>'),
            $this->a('Tại sao giá bạc biến động mạnh hơn vàng?','Hiểu về đặc tính biến động của bạc giúp nhà đầu tư quản lý rủi ro tốt hơn.','<h2>Bạc — Kim loại với hai vai trò</h2><p>Bạc vừa là kim loại quý vừa là kim loại công nghiệp. Điều này khiến giá bạc chịu ảnh hưởng từ nhiều yếu tố hơn vàng và có biên độ dao động lớn hơn.</p><h3>Thị trường nhỏ hơn</h3><p>Thị trường bạc có quy mô nhỏ hơn nhiều so với vàng, nên cùng một dòng vốn sẽ tạo ra biến động giá lớn hơn.</p><h3>Nhu cầu công nghiệp</h3><p>Khoảng 50% nhu cầu bạc đến từ công nghiệp. Khi kinh tế tăng trưởng, nhu cầu bạc tăng mạnh; khi suy thoái, nhu cầu giảm nhanh. Điều này tạo ra biến động mà vàng không có.</p>'),
            $this->a('Lạm phát và tác động đến giá vàng: Mối quan hệ phức tạp','Phân tích mối tương quan giữa lạm phát và giá vàng qua các giai đoạn lịch sử.','<h2>Vàng và lạm phát</h2><p>Vàng từ lâu được coi là công cụ phòng ngừa lạm phát hiệu quả. Tuy nhiên, mối quan hệ này phức tạp hơn nhiều người nghĩ.</p><h3>Khi lạm phát tăng</h3><p>Trong môi trường lạm phát cao, giá vàng thường tăng vì nhà đầu tư tìm kiếm tài sản giữ giá trị. Đây là lý do vàng tăng mạnh trong giai đoạn lạm phát đình đốn (stagflation).</p><h3>Khi lãi suất tăng</h3><p>Tuy nhiên, nếu ngân hàng trung ương tăng lãi suất mạnh để kiểm soát lạm phát, vàng có thể giảm vì chi phí cơ hội nắm giữ vàng tăng lên.</p>'),
            $this->a('Xu hướng vàng 2026: Các tổ chức lớn dự báo gì?','Tổng hợp dự báo giá vàng từ Goldman Sachs, JP Morgan, ANZ và nhiều tổ chức tài chính hàng đầu.','<h2>Dự báo giá vàng 2026</h2><p>Hầu hết các tổ chức tài chính lớn đều lạc quan về triển vọng giá vàng trong năm 2026.</p><h3>Goldman Sachs: 5.500 USD</h3><p>Goldman Sachs dự báo vàng có thể đạt 5.500 USD/ounce vào cuối năm, dựa trên nhu cầu từ ngân hàng trung ương và rủi ro địa chính trị.</p><h3>ANZ: 5.800 USD</h3><p>ANZ lạc quan hơn với mục tiêu 5.800 USD, cho rằng Fed sẽ phải cắt giảm lãi suất trong nửa cuối năm.</p><h3>JP Morgan: 5.200 USD</h3><p>JP Morgan thận trọng hơn, lưu ý rằng đồng USD mạnh có thể hạn chế đà tăng của vàng.</p>'),
            $this->a('Bạc trong công nghệ: Nhu cầu tăng từ pin mặt trời và xe điện','Nhu cầu bạc trong công nghiệp đang bùng nổ, đặc biệt từ lĩnh vực năng lượng xanh.','<h2>Bạc — Kim loại của tương lai xanh</h2><p>Bạc đóng vai trò quan trọng trong cuộc cách mạng năng lượng xanh. Mỗi tấm pin mặt trời cần khoảng 20g bạc, và nhu cầu đang tăng theo cấp số nhân.</p><h3>Pin năng lượng mặt trời</h3><p>Ngành công nghiệp năng lượng mặt trời tiêu thụ khoảng 150 triệu ounce bạc mỗi năm, chiếm hơn 15% tổng cung bạc toàn cầu.</p><h3>Xe điện</h3><p>Mỗi chiếc xe điện sử dụng nhiều bạc hơn xe xăng do hệ thống điện tử phức tạp hơn. Với sự bùng nổ xe điện, nhu cầu bạc sẽ tiếp tục tăng.</p>'),
            $this->a('Cách đọc biểu đồ giá vàng cho người mới bắt đầu','Hướng dẫn cơ bản cách đọc và phân tích biểu đồ giá vàng để đưa ra quyết định đầu tư.','<h2>Đọc biểu đồ giá vàng</h2><p>Biểu đồ giá vàng là công cụ quan trọng giúp nhà đầu tư hiểu xu hướng thị trường. Bài viết này hướng dẫn cách đọc cho người mới.</p><h3>Biểu đồ nến Nhật</h3><p>Mỗi cây nến thể hiện giá mở cửa, đóng cửa, cao nhất và thấp nhất trong một khoảng thời gian. Nến xanh = giá tăng, nến đỏ = giá giảm.</p><h3>Đường trung bình động (MA)</h3><p>MA20 và MA50 là hai đường trung bình phổ biến. Khi MA20 cắt lên MA50, đó là tín hiệu mua (Golden Cross).</p><h3>Mức hỗ trợ và kháng cự</h3><p>Hỗ trợ là vùng giá mà lực mua mạnh lên, kháng cự là vùng giá mà lực bán mạnh lên. Xác định đúng các mức này giúp timing tốt hơn.</p>'),
            $this->a('Đồng USD suy yếu: Tín hiệu tích cực cho vàng','Chỉ số DXY giảm về mức thấp nhất 6 tháng, tạo động lực cho vàng tăng giá.','<h2>USD yếu, vàng mạnh</h2><p>Chỉ số Dollar Index (DXY) vừa giảm xuống 98,5 — mức thấp nhất trong 6 tháng. Đây là yếu tố hỗ trợ tích cực cho giá vàng.</p><h3>Mối quan hệ nghịch</h3><p>Vàng được định giá bằng USD nên khi USD yếu, vàng trở nên rẻ hơn với người mua quốc tế, từ đó thúc đẩy nhu cầu. Mối quan hệ nghịch này đã được kiểm chứng qua nhiều thập kỷ.</p>'),
            $this->a('Vàng nhẫn vs vàng miếng: Nên mua loại nào để đầu tư?','So sánh chi tiết ưu nhược điểm của vàng nhẫn trơn và vàng miếng SJC.','<h2>Vàng nhẫn hay vàng miếng?</h2><p>Đây là câu hỏi thường gặp nhất của người mới đầu tư vàng tại Việt Nam.</p><h3>Vàng miếng SJC</h3><p>Ưu điểm: thanh khoản cao, được chấp nhận rộng rãi. Nhược điểm: chênh lệch mua-bán lớn (1-2 triệu/lượng), giá premium cao so với thế giới.</p><h3>Vàng nhẫn trơn</h3><p>Ưu điểm: giá sát thế giới hơn, chênh lệch mua-bán nhỏ hơn, dễ chia nhỏ. Nhược điểm: một số tiệm vàng nhỏ có thể không mua lại.</p><h3>Kết luận</h3><p>Vàng nhẫn 999.9 là lựa chọn thông minh hơn cho hầu hết nhà đầu tư cá nhân.</p>'),
            $this->a('Fed giữ nguyên lãi suất: Tác động gì đến thị trường vàng?','Cục Dự trữ Liên bang Mỹ giữ lãi suất ở mức 4.5-4.75%, thị trường phản ứng tích cực.','<h2>Fed giữ nguyên lãi suất</h2><p>Trong cuộc họp FOMC tháng 3/2026, Fed quyết định giữ nguyên lãi suất ở mức 4,5-4,75%. Quyết định này phù hợp với kỳ vọng thị trường.</p><h3>Tác động đến vàng</h3><p>Giá vàng tăng nhẹ sau quyết định, khi thị trường kỳ vọng Fed sẽ cắt giảm lãi suất từ quý 3. Lãi suất thấp hơn thường có lợi cho vàng vì giảm chi phí cơ hội nắm giữ.</p>'),
            $this->a('Cách bảo quản vàng và bạc tại nhà an toàn','Hướng dẫn cách lưu trữ kim loại quý tại nhà đúng cách, tránh rủi ro mất mát.','<h2>Bảo quản kim loại quý</h2><p>Nếu bạn chọn lưu trữ vàng bạc tại nhà thay vì gửi ngân hàng, cần lưu ý một số vấn đề quan trọng.</p><h3>Két sắt chuyên dụng</h3><p>Đầu tư một chiếc két sắt chống cháy, chống nước là bắt buộc. Chọn loại nặng, khó di chuyển và có khóa điện tử.</p><h3>Bảo quản bạc</h3><p>Bạc dễ bị oxy hóa (xỉn đen) khi tiếp xúc với không khí. Nên bọc bạc trong giấy chống oxy hóa hoặc túi zip hút chân không.</p><h3>Bảo hiểm</h3><p>Mua bảo hiểm cho kim loại quý lưu trữ tại nhà là điều cần thiết, đặc biệt khi giá trị lớn.</p>'),
            $this->a('Thị trường bạc thế giới: Thiếu hụt nguồn cung năm thứ 4 liên tiếp','Silver Institute cảnh báo tình trạng thiếu hụt bạc đang ngày càng nghiêm trọng.','<h2>Thiếu hụt bạc kéo dài</h2><p>Theo Silver Institute, thị trường bạc thế giới đã thiếu hụt nguồn cung năm thứ 4 liên tiếp trong 2025, với mức thiếu hụt khoảng 150 triệu ounce.</p><h3>Nhu cầu vượt cung</h3><p>Tổng nhu cầu bạc toàn cầu đạt 1,2 tỷ ounce, trong khi tổng cung chỉ đạt 1,05 tỷ ounce. Khoảng cách này đang được bù đắp bằng tồn kho, nhưng tồn kho đang cạn dần.</p><h3>Tác động giá</h3><p>Thiếu hụt kéo dài sẽ tạo áp lực tăng giá bạc trong trung và dài hạn, đặc biệt khi nhu cầu công nghiệp tiếp tục tăng.</p>'),
            $this->a('Đầu tư vàng qua ETF: Ưu nhược điểm so với mua vàng vật chất','Phân tích chi tiết hai hình thức đầu tư vàng phổ biến nhất hiện nay.','<h2>Vàng vật chất vs Vàng ETF</h2><p>Có hai cách chính để đầu tư vàng: mua vàng vật chất hoặc mua quỹ ETF vàng. Mỗi cách có ưu nhược điểm riêng.</p><h3>Vàng vật chất</h3><p>Ưu điểm: sở hữu trực tiếp, không rủi ro đối tác. Nhược điểm: phí bảo quản, chênh lệch mua-bán, rủi ro trộm cắp.</p><h3>Vàng ETF</h3><p>Ưu điểm: thanh khoản cao, giao dịch nhanh, phí thấp. Nhược điểm: không sở hữu vàng thật, phụ thuộc vào sàn giao dịch.</p>'),
            $this->a('Tại sao ngân hàng trung ương trên toàn cầu đang tích trữ vàng?','Xu hướng de-dollarization thúc đẩy các quốc gia tăng cường mua vàng dự trữ.','<h2>Làn sóng mua vàng toàn cầu</h2><p>Từ năm 2022, các ngân hàng trung ương trên thế giới đã mua hơn 3.000 tấn vàng — một con số chưa từng có trong lịch sử.</p><h3>Lý do chính</h3><p>Xu hướng giảm phụ thuộc vào đồng USD (de-dollarization) là động lực lớn nhất. Sau khi Mỹ đóng băng tài sản Nga, nhiều quốc gia bắt đầu đa dạng hóa dự trữ.</p>'),
            $this->a('Phân tích giá bạc: Mức 40 USD/ounce có khả thi trong 2026?','Đánh giá khả năng bạc phá mốc 40 USD dựa trên phân tích cung cầu và kỹ thuật.','<h2>Bạc hướng tới 40 USD?</h2><p>Với đà tăng hiện tại, nhiều chuyên gia đặt câu hỏi liệu bạc có thể phá mốc 40 USD/ounce trong năm nay.</p><h3>Yếu tố hỗ trợ</h3><p>Thiếu hụt nguồn cung, nhu cầu công nghiệp tăng, và vai trò trú ẩn an toàn đều hỗ trợ giá bạc. Tỷ lệ vàng/bạc ở mức cao cũng cho thấy bạc còn dư địa tăng.</p><h3>Rào cản</h3><p>Tuy nhiên, nếu kinh tế suy thoái, nhu cầu công nghiệp giảm có thể kéo giá bạc xuống. Mốc 40 USD khả thi nhưng cần nhiều yếu tố thuận lợi đồng thời.</p>'),
            $this->a('Cập nhật giá vàng bạc tuần 11-15/3: Biến động và nhận định','Tổng hợp diễn biến giá vàng bạc trong tuần và dự báo tuần tới.','<h2>Tổng kết tuần giao dịch</h2><p>Vàng tăng 2,3% trong tuần qua, đóng cửa ở 5.120 USD/ounce. Bạc tăng 3,1%, đạt 37,8 USD/ounce. Cả hai kim loại quý đều hưởng lợi từ đồng USD yếu.</p><h3>Sự kiện quan trọng</h3><p>Báo cáo GDP quý 4 của Mỹ tăng 0,7% — thấp hơn kỳ vọng, làm dấy lên lo ngại về stagflation. Đây là yếu tố tích cực cho vàng.</p><h3>Tuần tới</h3><p>Thị trường chờ đợi báo cáo CPI và quyết định lãi suất của ECB. Dự kiến biến động lớn.</p>'),
            $this->a('Bạc 999 là gì? Tìm hiểu các loại bạc phổ biến trên thị trường','Giải thích các loại ký hiệu bạc 999, 925, 900 và cách phân biệt.','<h2>Các loại bạc thông dụng</h2><p>Trên thị trường có nhiều loại bạc với độ tinh khiết khác nhau. Hiểu rõ sự khác biệt giúp bạn đưa ra quyết định mua đúng.</p><h3>Bạc 999 (Fine Silver)</h3><p>Bạc nguyên chất 99,9%, mềm và dễ trầy xước. Chủ yếu dùng cho đầu tư (thị, nhẫn trơn). Đây là tiêu chuẩn giao dịch quốc tế.</p><h3>Bạc 925 (Sterling Silver)</h3><p>Hợp kim gồm 92,5% bạc + 7,5% đồng. Cứng hơn bạc 999, phổ biến trong trang sức. Không phù hợp cho đầu tư.</p>'),
            $this->a('Kinh tế Mỹ chậm lại: Cơ hội cho vàng bứt phá','GDP Mỹ tăng trưởng chậm kết hợp lạm phát cao tạo ra kịch bản hoàn hảo cho vàng.','<h2>Stagflation — kịch bản hoàn hảo cho vàng</h2><p>Kinh tế Mỹ đang trong trạng thái stagflation — tăng trưởng chậm nhưng lạm phát vẫn cao. Đây là môi trường lý tưởng cho vàng.</p><h3>Lịch sử cho thấy gì?</h3><p>Trong giai đoạn stagflation 1970s, giá vàng đã tăng hơn 1.400% từ 35 USD lên 850 USD/ounce. Dù lịch sử không lặp lại chính xác, nhưng xu hướng tương tự có thể xảy ra.</p>'),
            $this->a('Top 5 quốc gia sản xuất bạc lớn nhất thế giới','Mexico, Peru và Trung Quốc dẫn đầu sản xuất bạc toàn cầu.','<h2>Các quốc gia sản xuất bạc hàng đầu</h2><h3>1. Mexico — 200 triệu ounce/năm</h3><p>Mexico là nước sản xuất bạc lớn nhất thế giới, chiếm khoảng 20% tổng sản lượng toàn cầu.</p><h3>2. Peru — 145 triệu ounce/năm</h3><p>Peru đứng thứ hai với các mỏ bạc khổng lồ tại vùng Andes.</p><h3>3. Trung Quốc — 110 triệu ounce/năm</h3><p>Trung Quốc vừa sản xuất vừa tiêu thụ bạc lớn, phần lớn cho công nghiệp.</p><h3>4. Chile — 55 triệu ounce</h3><p>Chile chủ yếu khai thác bạc phụ phẩm từ mỏ đồng.</p><h3>5. Bolivia — 50 triệu ounce</h3><p>Bolivia có lịch sử khai thác bạc lâu đời từ thời thuộc địa Tây Ban Nha.</p>'),
            $this->a('Vàng kỹ thuật số vs vàng vật chất: Xu hướng đầu tư mới','Các nền tảng mua bán vàng kỹ thuật số đang thu hút giới trẻ Việt Nam.','<h2>Vàng kỹ thuật số là gì?</h2><p>Vàng kỹ thuật số (digital gold) cho phép bạn mua bạn vàng từ 0,01 gram qua ứng dụng di động. Vàng thật được lưu trữ tại kho bảo mật, bạn chỉ sở hữu quyền sở hữu.</p><h3>Ưu điểm</h3><p>Mua bán 24/7, vốn nhỏ từ vài chục nghìn đồng, không cần lo bảo quản. Rất phù hợp cho người trẻ bắt đầu tích lũy.</p><h3>Nhược điểm</h3><p>Phụ thuộc nền tảng trung gian, rủi ro pháp lý chưa rõ ràng tại Việt Nam.</p>'),
            $this->a('Ảnh hưởng của chiến tranh thương mại đến giá vàng','Căng thẳng thương mại Mỹ-Trung tạo ra bất ổn toàn cầu, đẩy giá vàng lên cao.','<h2>Chiến tranh thương mại và vàng</h2><p>Căng thẳng thương mại giữa Mỹ và Trung Quốc là một trong những yếu tố chính đẩy giá vàng lên cao trong những năm gần đây.</p><h3>Cơ chế tác động</h3><p>Thuế quan cao hơn → lạm phát tăng + tăng trưởng chậm → nhà đầu tư tìm tài sản an toàn → vàng tăng giá. Đây là chuỗi phản ứng đã được chứng minh qua nhiều đợt căng thẳng.</p>'),
            $this->a('Hướng dẫn kiểm tra vàng thật giả đơn giản tại nhà','Các phương pháp đơn giản giúp bạn phân biệt vàng thật và vàng giả.','<h2>Cách kiểm tra vàng thật</h2><h3>1. Test nam châm</h3><p>Vàng thật không bị hút bởi nam châm. Nếu sản phẩm bị hút, đó chắc chắn là vàng giả.</p><h3>2. Test gốm sứ</h3><p>Cọ vàng lên mặt gốm chưa tráng men. Vàng thật để lại vệt vàng, vàng giả để lại vệt đen.</p><h3>3. Test axit</h3><p>Nhỏ axit nitric lên vàng. Vàng thật không phản ứng, kim loại giả sẽ sủi bọt hoặc đổi màu. Cách này chỉ nên thực hiện bởi chuyên gia.</p><h3>4. Kiểm tra ký hiệu</h3><p>Vàng SJC và các thương hiệu uy tín luôn có ký hiệu tuổi vàng (999.9, 9999) trên sản phẩm.</p>'),
            $this->a('Bạc và năng lượng mặt trời: Mối liên hệ ít người biết','Ngành năng lượng mặt trời đang tiêu thụ lượng bạc khổng lồ mỗi năm.','<h2>Bạc trong pin mặt trời</h2><p>Ít ai biết rằng bạc là thành phần không thể thiếu trong sản xuất pin mặt trời. Bạc được sử dụng làm lớp dẫn điện trên tấm pin nhờ khả năng dẫn điện tốt nhất trong các kim loại.</p><h3>Con số ấn tượng</h3><p>Năm 2025, ngành năng lượng mặt trời tiêu thụ khoảng 160 triệu ounce bạc, tăng 15% so với năm trước. Với mục tiêu Net Zero, con số này dự kiến đạt 250 triệu ounce vào 2030.</p>'),
            $this->a('Giá vàng và bầu cử Mỹ: Lịch sử cho thấy điều gì?','Phân tích tác động của các kỳ bầu cử tổng thống Mỹ đến giá vàng.','<h2>Bầu cử và giá vàng</h2><p>Bầu cử tổng thống Mỹ thường tạo ra bất ổn chính sách, ảnh hưởng đến thị trường tài chính và giá vàng.</p><h3>Quy luật chung</h3><p>Giá vàng thường tăng trong năm bầu cử do sự bất định về chính sách. Sau bầu cử, vàng có thể điều chỉnh khi thị trường đã "định giá" kết quả.</p>'),
            $this->a('Mua bạc ở đâu uy tín tại Việt Nam? Top 5 thương hiệu','Danh sách các thương hiệu bạc uy tín nhất Việt Nam cho nhà đầu tư.','<h2>Top thương hiệu bạc uy tín</h2><h3>1. Phú Quý 999</h3><p>Thương hiệu lâu đời nhất, giá cạnh tranh, thanh khoản cao với hệ thống cửa hàng rộng khắp.</p><h3>2. Ancarat 999</h3><p>Thương hiệu mới nhưng phát triển nhanh, sản phẩm đa dạng từ nhẫn đến thỏi bạc.</p><h3>3. DOJI 99.9</h3><p>Thương hiệu trang sức lớn, có bán bạc đầu tư với chất lượng đảm bảo.</p><h3>4. Kim Ngân Phúc 999</h3><p>Chuyên về bạc đầu tư, giá sát thế giới nhất trong các thương hiệu.</p><h3>5. SJC</h3><p>Thương hiệu quốc gia, tuy chuyên về vàng nhưng cũng cung cấp bạc chất lượng cao.</p>'),
            $this->a('Tỷ lệ vàng/bạc: Chỉ báo quan trọng cho nhà đầu tư','Hiểu về Gold/Silver Ratio và cách sử dụng để tối ưu danh mục kim loại quý.','<h2>Gold/Silver Ratio là gì?</h2><p>Tỷ lệ vàng/bạc (Gold/Silver Ratio) cho biết cần bao nhiêu ounce bạc để mua một ounce vàng. Đây là chỉ báo quan trọng giúp nhà đầu tư quyết định nên mua vàng hay bạc.</p><h3>Diễn giải</h3><p>Trung bình lịch sử là khoảng 60-70:1. Khi tỷ lệ cao hơn (ví dụ 130:1), bạc đang rẻ tương đối so với vàng và có tiềm năng tăng giá nhiều hơn. Ngược lại, khi tỷ lệ thấp, vàng hấp dẫn hơn.</p>'),
        ];
    }

    private function a($title, $des, $content): array
    {
        return [$title, $des, $content];
    }
}
